openai:
  chatgpt:
    model: gpt-3.5-turbo
    api:
      key: REPLACE_WITH_YOUR_API_KEY
      url: https://api.openai.com/v1/chat/completions
    max-completions: 1
    temperature: 0
    max_tokens: 100

